version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    command:
      - mysqld
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=djangoblog
      - MYSQL_ROOT_PASSWORD=DjAnGoBlOg!2!Q@W#E
    ports:
      - "3302:3306"
    expose:
      - "3306"
    networks:
      - backnet
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    depends_on:
      - memcached
    container_name: db

  db2:
    image: mysql:8.0
    restart: always
    command:
      - mysqld
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=liaoqian_mysql_db
      - MYSQL_ROOT_PASSWORD=liaoqianhurryup
    ports:
      - "3303:3306"
    expose:
      - "3306"
    networks:
      - backnet
    volumes:
      - ./bin/datas/liaoqian_mysql_db/:/var/lib/mysql
    container_name: db

  djangoblog:
    build: .
    restart: always
    command: /code/DjangoBlog/bin/docker_start.sh
    # command: python manage.py runserver 0.0.0.0:8000
#    command: daphne -b 0.0.0.0 -p 8000 DjangoBlog.asgi:application
    ports:
      - "8003:8003"
      - "8000:8000"
    expose:
      - "8000"
      - "8003"
    volumes:
      - /root/DjangoBlog/:/code/DjangoBlog/
      - ./collectedstatic:/code/DjangoBlog/collectedstatic
    environment:
      - DJANGO_MYSQL_DATABASE=djangoblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=DjAnGoBlOg!2!Q@W#E
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_MEMCACHED_LOCATION=memcached:11211
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
    container_name: djangoblog


  nginx:
    restart: always
    image: nginx:1.22.0
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./collectedstatic:/code/DjangoBlog/collectedstatic
    networks:
      - frontnet
    container_name: nginx

  memcached:
    restart: always
    image: memcached:latest
    networks:
      - backnet
    container_name: memcached
    ports:
      - "11211:11211"

  blog_redis_service:
    restart: always
    image: redis:6
    networks:
      - backnet
    container_name: blog_redis
    expose:
      - "6379"

networks:
  backnet:
  frontnet:
