# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maven_to_nexus2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(432, 324)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(43, 30, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 160, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 54, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_folder = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_folder.setGeometry(QtCore.QRect(130, 30, 181, 20))
        self.lineEdit_folder.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_folder.setStyleSheet("border-color: rgb(0, 170, 0);")
        self.lineEdit_folder.setInputMask("")
        self.lineEdit_folder.setObjectName("lineEdit_folder")
        self.lineEdit_url = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_url.setGeometry(QtCore.QRect(130, 70, 181, 20))
        self.lineEdit_url.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_url.setStyleSheet("border-color: rgb(85, 170, 0);")
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.lineEdit_repository = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_repository.setGeometry(QtCore.QRect(130, 110, 181, 20))
        self.lineEdit_repository.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_repository.setStyleSheet("border-color: rgb(85, 170, 0);")
        self.lineEdit_repository.setObjectName("lineEdit_repository")
        self.lineEdit_user = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_user.setGeometry(QtCore.QRect(130, 150, 181, 20))
        self.lineEdit_user.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_user.setStyleSheet("border-color: rgb(85, 170, 0);")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_pwd = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(130, 190, 181, 20))
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_pwd.setStyleSheet("border-color: rgb(85, 170, 0);")
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setGeometry(QtCore.QRect(340, 30, 75, 23))
        self.selectButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:white;\n"
"font-size:14px;")
        self.selectButton.setObjectName("selectButton")
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setGeometry(QtCore.QRect(160, 280, 75, 23))
        self.confirmButton.setStyleSheet("background-color:rgb(0, 170, 255);\n"
"")
        self.confirmButton.setObjectName("confirmButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 371, 20))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "本地依赖库"))
        self.label_2.setText(_translate("Dialog", "私服地址"))
        self.label_3.setText(_translate("Dialog", "私服仓库"))
        self.label_4.setText(_translate("Dialog", "私服账号"))
        self.label_5.setText(_translate("Dialog", "私服密码"))
        self.lineEdit_folder.setToolTip(_translate("Dialog", "<html><head/><body><p>本地maven仓库路径</p></body></html>"))
        self.lineEdit_folder.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_folder.setText(_translate("Dialog", "D:/apache-maven-3.8.8/res2"))
        self.lineEdit_url.setToolTip(_translate("Dialog", "<html><head/><body><p>私服地址</p></body></html>"))
        self.lineEdit_url.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_url.setText(_translate("Dialog", "http://localhost:8931/"))
        self.lineEdit_repository.setToolTip(_translate("Dialog", "<html><head/><body><p>私有仓库名称</p></body></html>"))
        self.lineEdit_repository.setText(_translate("Dialog", "zj4"))
        self.lineEdit_user.setText(_translate("Dialog", "admin"))
        self.selectButton.setText(_translate("Dialog", "选择"))
        self.confirmButton.setText(_translate("Dialog", "确认"))
        self.label_6.setText(_translate("Dialog", "                           点击上传"))
